Update readme.md to include important info
Open-Science-Community-Saudi-Arabia/MOOCs pull request #90
Opened 2022-10-25 21:29 UTC by JulianaSau

### Summary

Fixes #70 

### List of changes proposed in this PR (pull-request)

* *Updated readme to include information important to new contributors*
* *Updated readme to contain more information about the project and repository*

### What should a reviewer concentrate their feedback on?

- [ ] *If anything should be added or removed*
- [ ] Everything looks ok?

2022-10-26 05:00 UTC, JulianaSau commented
Hey @sandygudie, please review my pr

2022-10-26 07:12 UTC, sandygudie requested changes

2022-10-26 07:12 UTC, sandygudie commented on README.md
> +- Always, **Always** make pull requests to the **dev** branch, not the main branch. All pull requests to the main branch will not be merged.
Welldone @JulianaSau 
...."to the dev_team2 branch"...
please

2022-10-26 07:12 UTC, sandygudie commented on README.md
> +- Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.
The Vite app default port is 5173, it does not open at 3000 (unless customized)

2022-10-26 07:40 UTC, JulianaSau commented
Thanks for the review. I've updated the pr with the requested changes

2022-10-26 08:36 UTC, sandygudie approved these changes

2022-11-02 08:15 UTC, sandygudie approved these changes

2022-11-02 08:30 UTC, sandygudie commented
@BatoolMM this is ready for merging
Also, Please, if it's possible; I would like to request merge privilege for the MOOCs Frontend development so that development could be much faster. Thanks

2022-11-09 22:05 UTC, BatoolMM commented
@all-contributors please add @sandygudie for mentoring

2022-11-09 22:06 UTC, BatoolMM commented
Just saw this - you now have merge privileges for the MOOCs Frontend development.

2022-11-09 22:07 UTC, merged